# Generated by Django 4.0 on 2021-12-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bisiklet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Govde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('govde_ismi', models.CharField(max_length=100)),
                ('kadro', models.CharField(max_length=100)),
                ('vites', models.CharField(max_length=100)),
                ('kod', models.CharField(max_length=100)),
                ('tedarikci', models.CharField(max_length=100)),
                ('skt', models.CharField(max_length=100)),
                ('gelis_tarihi', models.CharField(max_length=100)),
                ('baglantili_parcalar', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sele_ismi', models.CharField(max_length=100)),
                ('renk', models.CharField(max_length=100)),
                ('kod', models.CharField(max_length=100)),
                ('tedarikci', models.CharField(max_length=100)),
                ('skt', models.CharField(max_length=100)),
                ('gelis_tarihi', models.CharField(max_length=100)),
                ('baglantili_parcalar', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tekerlek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teker_ismi', models.CharField(max_length=100)),
                ('jant', models.CharField(max_length=100)),
                ('lastik', models.CharField(max_length=100)),
                ('olcu', models.CharField(max_length=100)),
                ('kod', models.CharField(max_length=100)),
                ('tedarikci', models.CharField(max_length=100)),
                ('skt', models.CharField(max_length=100)),
                ('gelis_tarihi', models.CharField(max_length=100)),
                ('baglantili_parcalar', models.CharField(max_length=100)),
            ],
        ),
    ]
