# Generated by Django 4.0 on 2021-12-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bisiklet',
            name='govde_baglantili_parcalar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bisiklet',
            name='govde_gelis_tarihi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bisiklet',
            name='govde_ismi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bisiklet',
            name='govde_kod',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bisiklet',
            name='govde_skt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bisiklet',
            name='govde_tedarikci',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bisiklet',
            name='jant',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bisiklet',
            name='kadro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bisiklet',
            name='lastik',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bisiklet',
            name='olcu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bisiklet',
            name='renk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bisiklet',
            name='sele_baglantili_parcalar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bisiklet',
            name='sele_gelis_tarihi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bisiklet',
            name='sele_ismi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bisiklet',
            name='sele_kod',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bisiklet',
            name='sele_skt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bisiklet',
            name='sele_tedarikci',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bisiklet',
            name='teker_baglantili_parcalar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bisiklet',
            name='teker_gelis_tarihi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bisiklet',
            name='teker_ismi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bisiklet',
            name='teker_kod',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bisiklet',
            name='teker_skt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bisiklet',
            name='teker_tedarikci',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bisiklet',
            name='vites',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
